### ISSUE TITLE
Duplicate place order button

### ISSUE THREAD

**Issue by ennostuurman** [buckaroo-it/Magento2_Hyva#19] opened 2022-11-17 18:34 UTC
Not a bug but more of an issue from a UX POV.

In the current Buckaroo module the place order button will show up twice:  the Buckaroo and the original Hyva React Checkout place order button. See screenprint. That's probably confusing for the webshop customer.

![react-checkout-ideal-duplicate-place-order-button](https://user-images.githubusercontent.com/1906257/202529482-3415c5b4-99b0-4e97-a16d-2ced7364f25f.png)

**Comment by Buckaroo-Rene** [comment] 2023-05-09 12:32
@ennostuurman,
Thanks again for informing us about this issue. We've removed the second "place order" button.
So the issue is resolved in our release: https://github.com/buckaroo-it/Magento2_Hyva/releases/tag/v1.0.0

**Closed by Buckaroo-Rene** 2023-05-09 12:32 UTC
Labels: Bug, Priority: Normal
